services:
  java:
    build: .
    container_name: java_api
    ports:
      - "8080:8080"
    environment:
      DB_URI: jdbc:mariadb://mysql:3306/todo?allowPublicKeyRetrieval=true&useSSL=false
      DB_USERNAME: user
      DB_PASSWORD: 1234
      PORT: 8080
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - mysql_network

  mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge